# Generated by Django 3.2.5 on 2021-07-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='name',
        ),
    ]
