# Generated by Django 3.2.5 on 2021-07-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210722_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='rg',
            new_name='document',
        ),
    ]
