# Generated by Django 3.2.5 on 2021-07-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_rg_aluno_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Student',
        ),
    ]
